# docker-compose.yml

version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c 'python manage.py migrate & python manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./:/HackerNews2
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=den41k123
      - POSTGRES_DB=testtask
      - DB_HOST=127.0.0.1
      - DB_PORT=5432

volumes:
  postgres_data: