# Generated by Django 4.0.3 on 2022-03-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='amount_of_upvotes',
        ),
    ]
